name: venv-sofia-py27
channels:
  - conda-forge
  - free
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2025.2.25
  - cairo=1.12.18
  - certifi=2020.6.20
  - fontconfig=2.11.1
  - freetype=2.5.5
  - glib=2.43.0
  - harfbuzz=0.9.39
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgfortran=1.0
  - libgomp=11.2.0
  - libiconv=1.14
  - libpng=1.6.17
  - libstdcxx-ng=11.2.0
  - libxml2=2.9.4
  - matplotlib=1.4.3
  - mkl=11.3.3
  - ncurses=5.9
  - numpy=1.9.3
  - openssl=1.0.2u
  - pango=1.39.0
  - pip=19.3.1
  - pixman=0.32.6
  - py2cairo=1.10.0
  - pyparsing=2.0.3
  - pyqt=4.11.4
  - pyserial=3.4
  - python=2.7.14
  - python-dateutil=2.6.1
  - pytz=2017.2
  - qt=4.8.7
  - readline=7.0
  - scipy=0.16.0
  - setuptools=44.0.0
  - sip=4.18
  - six=1.10.0
  - sqlite=3.20.1
  - tk=8.6.14
  - wheel=0.37.1
  - xlwt=0.7.5
  - zlib=1.2.13
